---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: apollo-pv-5
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  # storageClassName:
  hostPath:
   path: "/mnt/apollo-l/5"
